version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "4000:4000"
    env_file:
      - "./backend/environment/.env"
      - "./backend/environment/.env"
      - "frontend.env"
    environment:
      - MONGO_DB_PASSWORD=sadjasdk12312321
    volumes:
      - backend_data/app/data
      - ./backend
      - ./backend/node_modules
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - BACKEND_ENDPOINT=HTTPS//RAILWAY.123.APPLICATION-ONE
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:

volumes:
  backend_data:
